# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'my-project'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
         - targets: ['localhost:9090']


  - job_name: 'cadvisor'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080

#     static_configs:
#          - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100
  - job_name: 'test-wmi-exporter'
    scrape_interval: 10s
    scrape_timeout: 5s
    static_configs:
      - targets: ['172.16.0.242:9182']
  - job_name: 'node'
    ec2_sd_configs:
      - region: ap-southeast-1
        port: 9182
    relabel_configs:
        # Only monitor instances with a Name starting with "SD Demo"
      - source_labels: [__meta_ec2_tag_Name]
        regex: scsc.*
        action: keep
        # Use the instance ID as the instance label
      - source_labels: [__meta_ec2_instance_id]
        target_label: instance  
  - job_name: 'blackbox'
    metrics_path: /metrics
    params:
      module: [http_2xx]
      target:
        - http://3.0.99.140
    static_configs:
      - targets:
          - 172.16.0.242:9115
   #   - targets:
   #     - http://3.0.99.140
   # relabel_configs:
   #   - source_labels: [__address__]
   #     target_label: __param_target
   #   - source_labels: [__param_target]
   #     target_label: instance
   #   - target_label: _address_
   #     replacement: 172.16.0.242:9115 # Blackbox exporter.
      #  - job_name: 'node_exporter'
      #    scrape_interval: 10s
      # scrape_timeout: 10s
      #ec2_sd_configs:
      #- region: ap-southeast-1
      # port: 9100
      #relabel_configs:
      #- source_labels: [__meta_ec2_tag_value]
      # regex: .*tag.*
      #  action: keep
      
#     static_configs:
#          - targets: ['node-exporter:9100']
